language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

notifications:
  on_success: change
  on_failure: change

# Miniconda-based setup of the Scipy stack Based on
# https://gist.github.com/dan-blanchard/7045057.

# Setup anaconda
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv

# Install packages
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then conda install --yes python=$TRAVIS_PYTHON_VERSION argparse; fi
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy # pysam
  - python setup.py install

script: python calculate_libsize.py example_duplicate_histo.txt

sudo: false
